### ISSUE TITLE
Map data needs to be updated

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/gcammaptools#5]
The geojson file for GCAM-USA is missing entirely, so that needs to be updated.  

The one for GCAM-China has a practical problem; it is painfully slow to render.  I think this is due to excessively high resolution in the China subregion boundaries:

```r
filter(map.chn, id<=32) %>% nrow / nrow(map.chn)
[1] 0.3350259
```

So, over 65% of the vertices in that data set are in the subregions (all of which have id values >= 33).  I think we could do with a bit less resolution in those subregion boundaries, especially if it speeds up map rendering.

Along those lines, all of the map data could have its resolution reduced a bit.  It's nice that we have all of the detail around the deltas of major rivers, all the islands of the Canadian arctic, and the fjords of Norway, but they don't really show up at the scales of our plots, and they slow the rendering dramatically.

**Comment by rplzzz** [comment]
@calebbraun Was this fixed in #27?  If so, then we can close this issue.  If not, then we'll leave it open to remind us to circle back to it when we're less busy.

**Comment by calebbraun** [comment]
There are now simplified versions of the map data, however GCAM-USA is still missing (although I have a shapefile that can be used for it, but it needs to be simplified and have non-US states removed). GCAM-China also should be revisited because the simplified map does not look good with the China extent, and the non-simplified one still has too much detail.

**Comment by rplzzz** [comment]
Ok, we'll leave this open to remind us.

**Comment by crvernon** [comment]
@calebbraun  @rplzzz We can remove the non-us states/provinces from the shapefile I sent you easily.  I will dissolve these tomorrow and send them to you.  As for GCAM-China, we can reduce the degree to which we simplify the original and perhaps apply a smoothing algorithm that will maintain the correct topology (no sliver polygons, etc.).  Point me to the GCAM-China file and I will take a look at this tomorrow as well.

**Comment by calebbraun** [comment]
@crvernon The GCAM-China file being used is in` inst/extdata/rgnchn/GCAM_China.geojson`

**Comment by calebbraun** [comment]
Those two pull requests add GCAM-USA map data, simplifies the GCAM-China map polygons, and removes the GCAM-China map that was oversimplified.

Examples for each of these maps still need to be added to the vignettes, but I have opened a separate issue for that (#35), so this one can be closed.
